travis:
  secure:
    BINSTAR_TOKEN: DzZZxdaXehuI9J+NFFW+oYkHuBIWwne8gUcTuLmq+kMPCRutSMfpblICiNc3ZBR2l0tRSwUWQoNEfVOojdYVsbCCT+HerlBOulnqWBzxG46Mu9xjz2DErWFbYTnrY79AWjAluDVUXtiJhpNjQLJTjFzMPMK3Xlb4xHTJezyveFLV3MynOajf4ae3HecJW5pwWvHYgpWBvXC/kzS1qZpbEIqHaAUOvJPPLJjAHWHAOMRQdrwPCEs7PezKxnKvWR36jveERfy9jGwPoJ4wl6xtm2nW9c7qlCuQaS0SweliXlTkXSyq1QQaNpzYWM7GxVP/gKNXHR8pAq2Fu/py9QVbzB7u+Q04ic6qFhcgq/XauwD0JL/SYl5lqdamEh7XjY0F2mjLbNeJ1kfWUEh7WXBoS2wZyVZbXIXRuWHCrr3qHk6DDxW0fVeUejxp6yih1Z7UNTO1AutztrWcbIOpzcDfacleVrtg4SM4O+doIpRvv2NowfzkQx1K3lE0xNHa+psRL99nxy6FYTRHxfPO44mXnZrhISQzXvncsSQN6Cxb27g1TILDRqXvexbNUMd2KHizC/QP5zi7qoTRf/qiS2Vzk1RzkQ8jRuVvrZP1Celp4toWRkEgZ/vGFhlcE4HySkl7K6DsoiIqcFoqFWx2li4IHs/Xo79qvaRs4yMerC+p5bQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
